version: '3.8'
services:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.2.2
    container_name: zookeeper-1
    hostname: zookeeper-1
    ports:
      - "2181:2181"
    environment:
      TZ: Asia/Tbilisi
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zk/secrets/zoo_jaas.conf
              -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    volumes:
      - ./zk/conf1:/etc/zk/secrets
    networks:
    - kafka-network
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
  kafka1:
    image: confluentinc/cp-kafka:7.2.2
    user: root
    container_name: kafka1
    hostname: kafka1
    restart: always
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Tbilisi
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181/test2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_1:SASL_PLAINTEXT
      KAFKA_LISTENERS: LISTENER_1://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_1://kafka1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_1
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf
      KAFKA_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - ./kafka/conf1:/etc/kafka/secrets
    networks:
    - kafka-network
  kafka2:
    image: confluentinc/cp-kafka:7.2.2
    user: root
    container_name: kafka2
    hostname: kafka2
    restart: always
    ports:
      - "9093:9093"
    environment:
      TZ: Asia/Tbilisi
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181/test2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_1:SASL_PLAINTEXT
      KAFKA_LISTENERS: LISTENER_1://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: LISTENER_1://kafka2:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_1
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf
      KAFKA_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - ./kafka/conf2:/etc/kafka/secrets
    networks:
    - kafka-network
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
  kafka-ui:
    user: root
    image: provectuslabs/kafka-ui
    networks:
    - kafka-network
    container_name: kafka-ui
    hostname: kafka-ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
    - zookeeper-1
    - kafka1
    environment:
      TZ: Asia/Tbilisi
      KAFKA_CLUSTERS_0_NAME: DataOpsKafkaLab
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092; kafka2:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required
        username="kafka-ui"
        password="fgtRz!";
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

networks:
    kafka-network:
       driver: bridge